ci: use bash loop instead of wait-on

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -71,7 +71,17 @@ jobs:
           EMAIL_PASS: "${{ secrets.EMAIL_PASS }}"
         run: |
           bun run start &
-          bunx wait-on http://localhost:3000 -t 5s && echo ok
+          max_wait_time=5
+          start_time=$(date +%s)
+          until curl -s -o /dev/null -w "%{http_code}" "http://localhost:3000/" | grep -q '200'; do
+            current_time=$(date +%s)
+            elapsed_time=$((current_time - start_time))
+            if [[ $elapsed_time -ge $max_wait_time ]]; then
+              echo "Error: Server failed to start within $max_wait_time seconds."
+              exit 1
+            fi
+            sleep 1
+          done
 
   lint:
     runs-on: ubuntu-latest
